// <auto-generated />
using System;
using HabitTracker.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HabitTracker.Api.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250403190241_FixedContentLinksSeedData")]
    partial class FixedContentLinksSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("HabitTracker.Api.Domain.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("HabitTracker.Api.Domain.ContentLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContentLinks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "No matter your goals, Atomic Habits offers a proven framework for improving--every day.",
                            Group = "home-sidebar",
                            SortOrder = 50,
                            Title = "Atomic Habit book",
                            Url = "https://amzn.to/3QXiHV5"
                        },
                        new
                        {
                            Id = 2,
                            Description = "How to help someone, the value of bad luck, and rewarding competence",
                            Group = "home-sidebar",
                            SortOrder = 40,
                            Title = "3-2-1 Newsletter",
                            Url = "https://jamesclear.com/3-2-1/march-20-2025"
                        },
                        new
                        {
                            Id = 5,
                            Description = "A habit is a routine of behavior that is repeated regularly and tends to occur subconsciously.",
                            Group = "home-sidebar",
                            SortOrder = 1,
                            Title = "History of Habits",
                            Url = "https://en.wikipedia.org/wiki/Habit"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Habits both good and bad—are closely related to our goals...",
                            Group = "home-sidebar",
                            SortOrder = 10,
                            Title = "17 Tips to Build Good Habits",
                            Url = "https://www.psychologytoday.com/us/blog/click-here-for-happiness/202106/17-tips-to-build-good-habits"
                        },
                        new
                        {
                            Id = 7,
                            Description = "On the surprising path to success...",
                            Group = "home-sidebar",
                            SortOrder = 5,
                            Title = "3-2-1 Newsletter",
                            Url = "https://jamesclear.com/3-2-1/march-27-2025"
                        },
                        new
                        {
                            Id = 10,
                            Description = "This book explores the science behind habit formation...",
                            Group = "home-sidebar",
                            SortOrder = 60,
                            Title = "The Power of Habit",
                            Url = "https://amzn.to/3FSTlp6"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Written by a behavioral scientist from Stanford...",
                            Group = "home-sidebar",
                            SortOrder = 70,
                            Title = "Tiny Habits",
                            Url = "https://amzn.to/426VXZf"
                        },
                        new
                        {
                            Id = 14,
                            Description = "The original book on building good habits...",
                            Group = "home-sidebar",
                            SortOrder = 80,
                            Title = "7 Habits of Highly Effective People",
                            Url = "https://amzn.to/4i2dM02"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Delving into the brain science behind habits...",
                            Group = "home-sidebar",
                            SortOrder = 30,
                            Title = "The Neuroscience of Habit Formation",
                            Url = "https://www.joincarbon.com/blog/the-neuroscience-of-habit-formation"
                        },
                        new
                        {
                            Id = 17,
                            Description = "This article discusses the distinction between habits and routines...",
                            Group = "home-sidebar",
                            SortOrder = 20,
                            Title = "What Does It Really Take to Build a New Habit?",
                            Url = "https://hbr.org/2021/02/what-does-it-really-take-to-build-a-new-habit"
                        });
                });

            modelBuilder.Entity("HabitTracker.Api.Domain.Habit", b =>
                {
                    b.Property<int>("HabitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.HasKey("HabitId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Habits");
                });

            modelBuilder.Entity("HabitTracker.Api.Domain.HabitCompletion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletionCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CompletionDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HabitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompletionDate");

                    b.HasIndex("HabitId");

                    b.ToTable("HabitCompletions");
                });

            modelBuilder.Entity("HabitTracker.Api.Domain.Weighing", b =>
                {
                    b.Property<int>("WeighingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("WeighingId");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("Weighings");
                });

            modelBuilder.Entity("HabitTracker.Api.Domain.Habit", b =>
                {
                    b.HasOne("HabitTracker.Api.Domain.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HabitTracker.Api.Domain.HabitCompletion", b =>
                {
                    b.HasOne("HabitTracker.Api.Domain.Habit", null)
                        .WithMany("DailyCompletions")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HabitTracker.Api.Domain.Habit", b =>
                {
                    b.Navigation("DailyCompletions");
                });
#pragma warning restore 612, 618
        }
    }
}
